# COMMENT: redirect rules with all the fields expanded
# According to netlify domain management
# https://app.netlify.com/sites/dukeslides/settings/domain#custom-domains
# Redirect default Netlify subdomain to primary domain
# http://dukeslides.netlify.com/* http://dukeslides.johnlittle.info/:splat 301!
[[redirects]]
  from = "https://dsvil.netlify.com/*"
  to = "https://dsvil.johnlittle.info/:splat"
  status = 301
  force = true