---
title: "README"
author: "John Little"
date: "`r Sys.Date()`"
output: github_document
---

## DSVIL2018
Supporting materials for DSVIL 2018, the Data Science &amp; Visualization Institute hosted by NCSU Libraries. June 6, 2018 https://johnlittle.info/

### Who / What

[Data Science And Visualization Institute for Librarians](https://www.lib.ncsu.edu/data-science-and-visualization-institute/). I am teaching modules on Data Cleaning, Web Scraping, HTML and JSON parsing, and Twitter Stream Gathering

### When

https://www.lib.ncsu.edu/data-science-and-visualization-institute/schedule

### Where

NCSU Libraries

### Why

Because data transformations are crazy-fun awesome

## Preface

- index
- introduction

### webscraping:  w/ webscraper.io  

- webscraping_10.html

### Data Cleaning:  Basic OpenRefine

- group demo / https://libjohn.github.io/openrefine/demonstration.html 
- Exercise 1:  [Basic Transformations](https://libjohn.github.io/openrefine/start.html)
- Excercise 2: GREL and regex Exercise 2 [GREL](https://libjohn.github.io/openrefine/grel.html)

### Data Cleaning:  Reconcilitation in OpenRefine

- [Reconciliation](https://libjohn.github.io/openrefine/hands-on-reconciliation.html)

### Twitter Streams with TAGS and GoogleSheets

- *** student needs google account
- *** student needs twitter account
- *** student needs twitter API keys ???
- http://www.johnlittle.info/project/custom/dsvil2017/slides.html#36 
through
- http://www.johnlittle.info/project/custom/dsvil2017/slides.html#45 

    - ***jrl*** add NodeXL https://www.smrfoundation.org/nodexl/ 
    - $29/student/month 
    - https://www.smrfoundation.org/license/ 


### API and twitter:  
- http://www.johnlittle.info/project/custom/dsvil2017/slides.html#47  

### Parsing HTML & JSON in OpenRefine (APIs)

- https://libjohn.github.io/openrefine/start.html#web-scraping 
- web scraping another way with OpenRefine (1.6)  
- http://v.gd/parsing2222  
        

### HTML
- http://www.johnlittle.info/project/custom/dsvil2017/slides.html#12 
through
- http://www.johnlittle.info/project/custom/dsvil2017/slides.html#19 
API & JSON (| HTML)
- http://www.johnlittle.info/project/custom/dsvil2017/slides.html#20 
- http://www.johnlittle.info/project/custom/dsvil2017/slides.html#35 

## Shareable / CC-BY-NC license

Data, presentation, and handouts are shareable under [CC BY-NC license](https://creativecommons.org/licenses/by-nc/4.0/)


     